 
# version format
version: 1.0.{build}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\trillek-client-core

# scripts that run after cloning repository
install:
  - ps: c:\projects\trillek-client-core\prebuild.ps1

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

build_script:
  - ps: c:\projects\trillek-client-core\build.ps1